

java:
  environment:
    DATA_STORE_DB_NAME: data-store
    DEFINITION_STORE_HOST: http://ccd-definition-store-${SERVICE_FQDN}
    USER_PROFILE_HOST: http://ccd-user-profile-api-${SERVICE_FQDN}
    # ROLE_ASSIGNMENT_URL: http://am-role-assignment-service-${SERVICE_FQDN}
    ROLE_ASSIGNMENT_URL: 
    ELASTIC_SEARCH_ENABLED: false # TODO
    ELASTIC_SEARCH_NODES_DISCOVERY_ENABLED: false # TODO
    ELASTIC_SEARCH_HOSTS: "{{ .Release.Name }}-es-master:9200"
    ELASTIC_SEARCH_DATA_NODES_HOSTS: "http://{{ .Release.Name }}-es-master:9200"
  postgresql:
    enabled: false

ccd:
  enabled: true
  ccd:
    s2s:
      enabled: false
    dataStore:
      enabled: false
    adminWeb:
      enabled: false
    definitionImporter:
      enabled: false
    userProfileImporter:
      enabled: false
    apiGatewayWeb:
      enabled: false
    ras:
      enabled: false # TODO
    elastic:
      enabled: false # TODO

  ingressHost: ${SERVICE_FQDN}

  global:
    ccdDefinitionStoreUrl: http://ccd-definition-store-${SERVICE_FQDN}
    ccdUserProfileUrl: http://ccd-user-profile-api-${SERVICE_FQDN}
    dmStoreUrl: http://dm-store-aat.service.core-compute-aat.internal
    idamApiUrl: https://idam-api.aat.platform.hmcts.net
    idamWebUrl: https://idam-web-public.aat.platform.hmcts.net
    s2sUrl: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    enableKeyVaults: true
    devMode: true

  ccd-definition-store-api:
    java:
      image: hmctspublic.azurecr.io/ccd/definition-store-api:latest
      imagePullPolicy: Always
      environment:
        ELASTIC_SEARCH_ENABLED: true
        ELASTIC_SEARCH_HOST: "{{ .Release.Name }}-es-master:9200"
        ELASTIC_SEARCH_FAIL_ON_IMPORT: true
      keyVaults:
        ccd:
          secrets:
            - ccd-definition-s2s-secret
  
  ccd-user-profile-api:
    java:
      image: hmctspublic.azurecr.io/ccd/user-profile-api:latest
      imagePullPolicy: Always
      keyVaults:
        ccd:
          secrets:
            - name: AppInsightsInstrumentationKey
              alias: azure.application-insights.instrumentation-key
        
  am-role-assignment-service:
    java:
      keyVaults: 
        am:
          secrets:
            - role-assignment-service-LD-SDK-KEY
